# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

btcrelay:
    stage: test
    script:
    - cd btcrelay-spec/docs; make html
    only:
    - branches
    except:
    - master

polkabtc:
    stage: test
    script:
    - cd polkabtc-spec/docs; make html
    only:
    - branches
    except:
    - master

pages:
    stage: deploy
    script:
    - cd btcrelay-spec/docs; make html; cd ../..
    - mv btcrelay-spec/docs/build/html/ public/btcrelay-spec/
    - cd polkabtc-spec/docs; make html; cd ../..
    - mv polkabtc-spec/docs/build/html/ public/polkabtc-spec/
    artifacts:
        paths:
        - public
    only:
    - master
    